Fix undefined emailBody error
Reproduction steps:
1. Create a campaign
2. Send the campaign
3. Create a second campaign
4. Send the second campaign -> encounter server error that
prevents sending of the second campaign + any subsequent campaigns:
TypeError: Cannot read property 'emailBody' of undefined

Caused by the listSubscriberModel.findAll (line 181) returning
an array whose length exceeded rateLimit_or_arrayOfIdsLength, because
ListSubscribers for additional campaigns were included.